name: CI Pipeline

on:
  push:
    branches:
      - ci-workflow-docker
env:
  IMAGE_NAME: people.webapp
  ACR_NAME: people
  ACR_LOGIN_SERVER: people.azurecr.io
  
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        
    - name: Login to Azure Container Registry
      run: |
        az acr login -n $ACR_NAME
        
    - name: Count existing tags
      id: count-tags
      run: |
        COUNT=$(az acr repository show-tags -n $ACR_NAME --repository $IMAGE_NAME -o tsv | wc -l)
        echo "IMAGE_TAG=v$COUNT+1" >> $GITHUB_ENV     
    
    - name: Build Docker image
      run: |
        docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG .
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:IMAGE_TAG
    
    - name: Logout from Azure Container Registry
      run: |
        docker logout $ACR_LOGIN_SERVER
    
    - name: Cleanup Docker images
      run: |
        docker image rm $ACR_LOGIN_SERVER/$IMAGE_NAME:IMAGE_TAG
